app = "tokopedia-scraper"
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  DB_HOST = ""
  DB_USER = ""
  DB_PASS = ""
  DB_NAME = ""
  PORT = "3000"

[processes]
  web = "node daemon-monitor.js"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
